export enum MarketOrderMarginCloseoutReason {
  MARGIN_CHECK_VIOLATION = 'MARGIN_CHECK_VIOLATION',
  REGULATORY_MARGIN_CALL_VIOLATION = 'REGULATORY_MARGIN_CALL_VIOLATION',
  REGULATORY_MARGIN_CHECK_VIOLATION = 'REGULATORY_MARGIN_CHECK_VIOLATION',
}
